server:
  port: 9999
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  zipkin:
    base-url: http://localhost:5000
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://peer1:8761/eureka/, http://peer2:8762/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug