spring:
  application:
    name: eureka-provider  # 注册到到eureka的应用名称
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_learning?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
  profiles:
    active: pro1
logging:
  level:
    root: info
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/, http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true



