server:
  port: 9000
spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yutingG/config-repo
          search-paths: config-repo
          username: #
          password: #
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka, http://peer2:8762/eureka