server:
  port: 9000
spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yutingG/config-repo
          search-paths: config-repo
          username: # github.name
          password: # github.pwd
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka, http://peer2:8762/eureka