server:
  port: 9000
spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yutingG/config-repo
          search-paths: config-repo
          username: # github账号
          password: # GitHub密码